name: Release

on:
  release:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jakejarvis/s3-sync-action@0.5.1
      with:
        args: --follow-symlinks 
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.REGION }}
        SOURCE_DIR: './target/debug/client.exe'
        DEST_DIR: $ {{ secrets.DEST_DIR }}
